In [1]:
#1
import numpy as np

In [2]:
#2
np.version.version

'1.22.3'

In [3]:
#3
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#4
print("number of elemnt:",x.size)
print("number of bytes occupied:",x.nbytes)


number of elemnt: 10
number of bytes occupied: 80


In [5]:
#5
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [6]:
#6
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
#7
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [8]:
#8
a[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [9]:
#9
a=np.arange(0,9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#10
x=np.array([1,2,4,0,1,0,0,4,10,0,1,1,0])
np.nonzero(x)

(array([ 0,  1,  2,  4,  7,  8, 10, 11], dtype=int64),)

In [11]:
#11
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#12
np.random.randint(0,9,size=(3,3,3))

array([[[1, 3, 5],
        [5, 3, 2],
        [2, 4, 6]],

       [[1, 1, 2],
        [8, 7, 2],
        [7, 3, 7]],

       [[0, 0, 6],
        [3, 7, 0],
        [8, 7, 4]]])

In [13]:
#13
a=np.random.randint(90,566,size=(10,10))
print(np.min(a))
print(np.max(a))

90
552


In [14]:
#14
rng=np.random.default_rng(10)
x=rng.random((30))
np.mean(x)

0.5663161660577832

In [15]:
#15
o=np.ones((5,5))
z=np.zeros((3,3))
o[1:4,1:4]=z
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#16
x=np.ones((5,5))
x[0]=0
x[-1]=0
x[:,0]=0
x[:,-1]=0
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#17
FALSE

In [17]:
#18
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [18]:
#19
z=np.ones((8,8))
z[1::2,::2]=0
z[::2,1::2]=0
z

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [19]:
#20
rng=np.random.default_rng(1000)
rng.random((6,7,8))
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [20]:
#21
np.tile([[1,0],[0,1]],(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [21]:
x=np.random.randint(2,10,size=(5,5))
x=(x-np.min(x))/(np.max(x)-np.min(x))
#x /=  x.sum(axis=1)[:,np.newaxis]
x

array([[0.14285714, 0.71428571, 0.42857143, 0.42857143, 0.57142857],
       [0.        , 0.42857143, 0.85714286, 0.28571429, 0.28571429],
       [0.85714286, 0.42857143, 0.42857143, 0.28571429, 0.85714286],
       [0.57142857, 0.28571429, 1.        , 0.        , 0.42857143],
       [0.57142857, 0.        , 1.        , 0.42857143, 0.28571429]])

In [22]:
color=np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [23]:
a=np.arange(1,16).reshape((5,3))
b=np.arange(1,7).reshape((3,2))
print(a)
print(b)
a@b

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

In [24]:
a=np.array([1,2,3,4,5,56,56,4,4,6,8,2,1])
a[np.nonzero((a>3) & (a<8))]*=-1
a

array([ 1,  2,  3, -4, -5, 56, 56, -4, -4, -6,  8,  2,  1])

In [25]:
print(sum(range(0,5),-1))
from numpy import *
print(sum(range(0,5),-1))

9
10


In [26]:
Z=array([1,2,3,4,5,6,7,8,9])
Z**Z
2 << Z >>2

array([  1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [27]:
#Z=np.array([1.000000002,2.00201,3.1222,4.123123,5.1231232,6.123312212],dtype=np.float64)
Z = np.random.uniform(-10,+10,10)

print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.ceil(np.abs(Z)))
#x=x.astype(int64)


[-3.5699677   7.95340791 -6.05801203  6.9239164   6.40650634 -8.48560868
  5.88927783 -7.27010214  4.3499877  -1.42254534]
[-4.  8. -7.  7.  7. -9.  6. -8.  5. -2.]
[4. 8. 7. 7. 7. 9. 6. 8. 5. 2.]


In [28]:
a=np.random.randint(1,25,size=(2,7))
b=np.random.randint(1,25,size=(7,4))
print(a)
print(b)
np.intersect1d(a,b)

[[ 8  3  8 22  8  3 22]
 [23  8 19  2  4 18 24]]
[[ 9 21  1 15]
 [ 7 12 19  1]
 [13 17  5 11]
 [12 24  8  6]
 [22 20 22 20]
 [ 3 22 19 23]
 [17 23 17 20]]


array([ 3,  8, 19, 22, 23, 24])

In [29]:

print(np.sqrt(-1))
np.emath.sqrt(-4)

nan


C:\Users\yuvar\AppData\Local\Temp\ipykernel_20968\501828943.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


2j

In [30]:
print(np.datetime64('today')+np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today')-np.timedelta64(1))

2022-04-10
2022-04-09
2022-04-08


In [31]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [32]:
a=np.ones(5)
b=np.ones(5)
np.divide(a,2,out=a)
np.add(a,b,out=b)
np.multiply(a,b,out=a)
a

array([0.75, 0.75, 0.75, 0.75, 0.75])

In [33]:
z=np.random.rand()

In [ ]:
tuymnbnbdfkdfnfnlfjkdklusrhgs;gr