In [4]:
#1
import numpy as np

In [5]:
#2
np.version.version

'1.22.3'

In [6]:
#3
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#4
print("number of elemnt:",x.size)
print("number of bytes occupied:",x.nbytes)


number of elemnt: 10
number of bytes occupied: 80


In [8]:
#5
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [9]:
#6
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
#7
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [11]:
#8
a[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [12]:
#9
a=np.arange(0,9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#10
x=np.array([1,2,4,0,1,0,0,4,10,0,1,1,0])
np.nonzero(x)

(array([ 0,  1,  2,  4,  7,  8, 10, 11], dtype=int64),)

In [14]:
#11
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#12
np.random.randint(0,9,size=(3,3,3))

array([[[6, 0, 6],
        [6, 0, 2],
        [7, 8, 4]],

       [[2, 4, 5],
        [7, 7, 3],
        [5, 5, 6]],

       [[7, 3, 2],
        [5, 1, 7],
        [1, 5, 1]]])

In [16]:
#13
a=np.random.randint(90,566,size=(10,10))
print(np.min(a))
print(np.max(a))

98
565


In [17]:
#14
rng=np.random.default_rng(10)
x=rng.random((30))
np.mean(x)

0.5663161660577832

In [18]:
#15
o=np.ones((5,5))
z=np.zeros((3,3))
o[1:4,1:4]=z
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#16
x=np.ones((5,5))
x[0]=0
x[-1]=0
x[:,0]=0
x[:,-1]=0
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
#18
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [21]:
#19
z=np.ones((8,8))
z[1::2,::2]=0
z[::2,1::2]=0
z

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [22]:
#20
rng=np.random.default_rng(1000)
rng.random((6,7,8))
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [23]:
#21
np.tile([[1,0],[0,1]],(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [24]:
x=np.random.randint(2,10,size=(5,5))
x=(x-np.min(x))/(np.max(x)-np.min(x))
#x /=  x.sum(axis=1)[:,np.newaxis]
x

array([[0.14285714, 0.57142857, 0.14285714, 0.57142857, 0.71428571],
       [0.42857143, 0.42857143, 0.85714286, 0.85714286, 0.        ],
       [0.42857143, 0.28571429, 1.        , 0.28571429, 0.        ],
       [0.85714286, 0.85714286, 0.42857143, 0.        , 0.42857143],
       [0.        , 0.71428571, 0.28571429, 1.        , 0.85714286]])

In [25]:
color=np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [26]:
a=np.arange(1,16).reshape((5,3))
b=np.arange(1,7).reshape((3,2))
print(a)
print(b)
a@b

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

In [27]:
a=np.array([1,2,3,4,5,56,56,4,4,6,8,2,1])
a[np.nonzero((a>3) & (a<8))]*=-1
a

array([ 1,  2,  3, -4, -5, 56, 56, -4, -4, -6,  8,  2,  1])

In [28]:
print(sum(range(0,5),-1))
from numpy import *
print(sum(range(0,5),-1))

9
10


In [29]:
Z=array([1,2,3,4,5,6,7,8,9])
Z**Z
2 << Z >>2

array([  1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [30]:
#Z=np.array([1.000000002,2.00201,3.1222,4.123123,5.1231232,6.123312212],dtype=np.float64)
Z = np.random.uniform(-10,+10,10)

print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.ceil(np.abs(Z)))
#x=x.astype(int64)


[ 1.23052099e+00  1.48855625e+00 -3.13270417e+00  7.82817626e-04
 -7.97925665e-02  9.79346600e+00 -2.76789182e+00  6.67335512e+00
  8.93940632e+00 -4.51933890e+00]
[ 2.  2. -4.  1. -1. 10. -3.  7.  9. -5.]
[ 2.  2.  4.  1.  1. 10.  3.  7.  9.  5.]


In [31]:
a=np.random.randint(1,25,size=(2,7))
b=np.random.randint(1,25,size=(7,4))
print(a)
print(b)
np.intersect1d(a,b)

[[ 2  3 23 22  9  6 14]
 [19 21  4  4  7  9  8]]
[[ 4 23  7  3]
 [18  2 17 16]
 [14 14  3 15]
 [17  8  7 15]
 [ 1  8 19  8]
 [ 6 21  2 16]
 [ 7 18 12  6]]


array([ 2,  3,  4,  6,  7,  8, 14, 19, 21, 23])

In [32]:

print(np.sqrt(-1))
np.emath.sqrt(-4)

nan


C:\Users\yuvar\AppData\Local\Temp\ipykernel_12388\501828943.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


2j

In [33]:
print(np.datetime64('today')+np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today')-np.timedelta64(1))

2022-04-11
2022-04-10
2022-04-09


In [34]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [35]:
a=np.ones(5)
b=np.ones(5)
np.divide(a,2,out=a)
np.add(a,b,out=b)
np.multiply(a,b,out=a)
a

array([0.75, 0.75, 0.75, 0.75, 0.75])

In [36]:
a = np.random.uniform(0,10,10)

print(a - a%1)
print(a // 1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[1. 5. 0. 0. 5. 3. 0. 9. 4. 9.]
[1. 5. 0. 0. 5. 3. 0. 9. 4. 9.]
[1. 5. 0. 0. 5. 3. 0. 9. 4. 9.]
[1 5 0 0 5 3 0 9 4 9]
[1. 5. 0. 0. 5. 3. 0. 9. 4. 9.]


In [37]:
a = np.zeros((5,5))
a += np.arange(5)
print(Z)


[ 1.23052099e+00  1.48855625e+00 -3.13270417e+00  7.82817626e-04
 -7.97925665e-02  9.79346600e+00 -2.76789182e+00  6.67335512e+00
  8.93940632e+00 -4.51933890e+00]


In [38]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:
b = np.random.random(10)
b.sort()
print(b)

[0.12209283 0.25205429 0.39339646 0.43200795 0.45379282 0.49133253
 0.50704268 0.66402796 0.90339657 0.92091041]


In [41]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
np.array_equal(A,B)
np.array_equiv(A,B)



[0 1 1 0 0] [1 0 1 1 0]


False

In [43]:
A = np.random.randint(0,2,5)
A.flags.writeable=None
A[0]=1
A


ValueError: assignment destination is read-only

In [44]:
a=np.random.randint(0,10,(10,2))
print(a)
x,y=a[:,0],a[:,1]
x,y
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
r,t

[[0 2]
 [8 9]
 [3 4]
 [6 1]
 [6 0]
 [3 5]
 [1 1]
 [5 9]
 [4 0]
 [6 0]]


(array([ 2.        , 12.04159458,  5.        ,  6.08276253,  6.        ,
         5.83095189,  1.41421356, 10.29563014,  4.        ,  6.        ]),
 array([1.57079633, 0.84415399, 0.92729522, 0.16514868, 0.        ,
        1.03037683, 0.78539816, 1.06369782, 0.        , 0.        ]))

In [45]:
a=random.randint(0,100,(10))
print(a)
a[np.argmax(a)]=0
a

[94 29 41 32 48 84 91 65  4 54]


array([ 0, 29, 41, 32, 48, 84, 91, 65,  4, 54])

In [46]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
