In [2]:
#1
import numpy as np

In [3]:
#2
np.version.version

'1.22.3'

In [4]:
#3
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#4
print("number of elemnt:",x.size)
print("number of bytes occupied:",x.nbytes)


number of elemnt: 10
number of bytes occupied: 80


In [6]:
#5
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [7]:
#6
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
#7
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [9]:
#8
a[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [10]:
#9
a=np.arange(0,9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#10
x=np.array([1,2,4,0,1,0,0,4,10,0,1,1,0])
np.nonzero(x)

(array([ 0,  1,  2,  4,  7,  8, 10, 11], dtype=int64),)

In [12]:
#11
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#12
np.random.randint(0,9,size=(3,3,3))

array([[[4, 6, 6],
        [0, 2, 5],
        [5, 6, 1]],

       [[2, 4, 6],
        [4, 4, 3],
        [3, 8, 5]],

       [[4, 6, 2],
        [1, 8, 3],
        [8, 4, 3]]])

In [14]:
#13
a=np.random.randint(90,566,size=(10,10))
print(np.min(a))
print(np.max(a))

95
548


In [15]:
#14
rng=np.random.default_rng(10)
x=rng.random((30))
np.mean(x)

0.5663161660577832

In [16]:
#15
o=np.ones((5,5))
z=np.zeros((3,3))
o[1:4,1:4]=z
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#16
x=np.ones((5,5))
x[0]=0
x[-1]=0
x[:,0]=0
x[:,-1]=0
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
#18
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
#19
z=np.ones((8,8))
z[1::2,::2]=0
z[::2,1::2]=0
z

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [20]:
#20
rng=np.random.default_rng(1000)
rng.random((6,7,8))
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [21]:
#21
np.tile([[1,0],[0,1]],(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [22]:
x=np.random.randint(2,10,size=(5,5))
x=(x-np.min(x))/(np.max(x)-np.min(x))
#x /=  x.sum(axis=1)[:,np.newaxis]
x

array([[0.        , 0.14285714, 0.85714286, 1.        , 0.28571429],
       [0.57142857, 0.28571429, 0.14285714, 0.        , 0.28571429],
       [0.42857143, 0.57142857, 0.85714286, 0.28571429, 0.14285714],
       [0.71428571, 1.        , 0.57142857, 0.57142857, 0.85714286],
       [0.85714286, 0.57142857, 0.85714286, 0.        , 0.28571429]])

In [23]:
color=np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [24]:
a=np.arange(1,16).reshape((5,3))
b=np.arange(1,7).reshape((3,2))
print(a)
print(b)
a@b

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

In [25]:
a=np.array([1,2,3,4,5,56,56,4,4,6,8,2,1])
a[np.nonzero((a>3) & (a<8))]*=-1
a

array([ 1,  2,  3, -4, -5, 56, 56, -4, -4, -6,  8,  2,  1])

In [26]:
print(sum(range(0,5),-1))
from numpy import *
print(sum(range(0,5),-1))

9
10


In [27]:
Z=array([1,2,3,4,5,6,7,8,9])
Z**Z
2 << Z >>2

array([  1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [28]:
#Z=np.array([1.000000002,2.00201,3.1222,4.123123,5.1231232,6.123312212],dtype=np.float64)
Z = np.random.uniform(-10,+10,10)

print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.ceil(np.abs(Z)))
#x=x.astype(int64)


[-6.21753733 -4.17725573 -3.02392901  6.63085267  5.37152474 -8.81733034
  3.88300672  1.09107728 -6.71400749 -1.51057736]
[-7. -5. -4.  7.  6. -9.  4.  2. -7. -2.]
[7. 5. 4. 7. 6. 9. 4. 2. 7. 2.]


In [29]:
a=np.random.randint(1,25,size=(2,7))
b=np.random.randint(1,25,size=(7,4))
print(a)
print(b)
np.intersect1d(a,b)

[[ 6 16  8 12 12 12 24]
 [ 1  5 17  5  4  8 17]]
[[12 24 19 17]
 [23  7  1  7]
 [ 3 12  3 12]
 [24 15  4 20]
 [19 16  1  3]
 [ 8 21  6  9]
 [24 24  2 20]]


array([ 1,  4,  6,  8, 12, 16, 17, 24])

In [30]:

print(np.sqrt(-1))
np.emath.sqrt(-4)

nan


C:\Users\yuvar\AppData\Local\Temp\ipykernel_12892\501828943.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


2j

In [31]:
print(np.datetime64('today')+np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today')-np.timedelta64(1))

2022-04-11
2022-04-10
2022-04-09


In [32]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [33]:
a=np.ones(5)
b=np.ones(5)
np.divide(a,2,out=a)
np.add(a,b,out=b)
np.multiply(a,b,out=a)
a

array([0.75, 0.75, 0.75, 0.75, 0.75])

In [34]:
a = np.random.uniform(0,10,10)

print(a - a%1)
print(a // 1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[7. 2. 2. 7. 8. 1. 3. 1. 1. 9.]
[7. 2. 2. 7. 8. 1. 3. 1. 1. 9.]
[7. 2. 2. 7. 8. 1. 3. 1. 1. 9.]
[7 2 2 7 8 1 3 1 1 9]
[7. 2. 2. 7. 8. 1. 3. 1. 1. 9.]


In [35]:
a = np.zeros((5,5))
a += np.arange(5)
print(Z)


[-6.21753733 -4.17725573 -3.02392901  6.63085267  5.37152474 -8.81733034
  3.88300672  1.09107728 -6.71400749 -1.51057736]


In [36]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [37]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [38]:
b = np.random.random(10)
b.sort()
print(b)

[0.05071904 0.34985276 0.40548226 0.5725491  0.5867375  0.60865226
 0.61914764 0.68097393 0.70377377 0.83189424]


In [39]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [40]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
np.array_equal(A,B)
np.array_equiv(A,B)



[0 1 1 0 0] [0 0 0 0 1]


False

In [41]:
A = np.random.randint(0,2,5)
A.flags.writeable=None
A[0]=1
A


ValueError: assignment destination is read-only

In [ ]:
a=np.random.randint(0,10,(10,2))
print(a)
x,y=a[:,0],a[:,1]
x,y
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
r,t

[[0 2]
 [8 9]
 [3 4]
 [6 1]
 [6 0]
 [3 5]
 [1 1]
 [5 9]
 [4 0]
 [6 0]]


(array([ 2.        , 12.04159458,  5.        ,  6.08276253,  6.        ,
         5.83095189,  1.41421356, 10.29563014,  4.        ,  6.        ]),
 array([1.57079633, 0.84415399, 0.92729522, 0.16514868, 0.        ,
        1.03037683, 0.78539816, 1.06369782, 0.        , 0.        ]))

In [ ]:
a=random.randint(0,100,(10))
print(a)
a[np.argmax(a)]=0
a

[94 29 41 32 48 84 91 65  4 54]


array([ 0, 29, 41, 32, 48, 84, 91, 65,  4, 54])

In [ ]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min,end=" ")
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min,end=" ")
   print(np.finfo(dtype).max)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
z = np.arange(100)
v = np.random.uniform(0,100)
print(z[(np.abs(Z-v)).argmin()])

68


In [ ]:

Z = np.zeros(10, [ ('position', [ ('x', float),('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
#X,Y = Z[:,0], Z[:,1]
print(X,Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.8933684  0.23451406 0.66644587 0.6018331  0.97254169 0.04479416
  0.02575498 0.02434355 0.19406497 0.02856681]] [[0.11110454 0.10593264 0.0922099  0.54373864 0.58901314 0.19977518
  0.32328557 0.79415287 0.66031004 0.04876852]]
[[0.         0.65887464 0.2277078  0.52169445 0.48442238 0.85319442
  0.89318186 1.10533217 0.88918613 0.8670453 ]
 [0.65887464 0.         0.43214975 0.57148699 0.88207231 0.21166025
  0.30136796 0.71959622 0.55585108 0.21373349]
 [0.2277078  0.43214975 0.         0.45612829 0.58353073 0.63088916
  0.68108794 0.95132503 0.73883793 0.63935658]
 [0.52169445 0.57148699 0.45612829 0.         0.37346304 0.65467797
  0.6168189  0.62944537 0.42410346 0.75738343]
 [0.48442238 0.88207231 0.58353073 0.37346304 0.         1.00609228
  0.98336983 0.97013506 0.78173478 1.08763635]
 [0.85319442 0.21166025 0.63088916 0.65467797 1.00609228 0.
  0.12496923 0.59472941 0.48412202 0.15187606]
 [0.89318186 0.30136796 0.68108794 0.6168189  0.98336983 0.12496923
  0.         0.470

In [ ]:
x = (np.random.rand(10)*100).astype(np.float32)
x = x.view(np.int32)
y[:] = x
print(y)

[1077441390 1104392764 1119143807 1112655566 1118247936 1079579896
 1110210285 1118741119 1118884081 1113403379]


In [ ]:
Z = np.genfromtxt('sample.txt', delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\yuvar\AppData\Local\Temp\ipykernel_12388\3095346764.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt('sample.txt', delimiter=",", dtype=np.int)


In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [42]:
x,y=np.meshgrid(np.linspace(-1,1,5),np.linspace(-1,1,5))

d=np.sqrt(x**2 + y**2)
s,mu=1.0,0.0
g=np.exp(-((d-mu)**2/2*s**2))
print(g)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


In [45]:
Z = np.zeros((10,10))
np.put(Z, np.random.choice(range(10*10), 25),9)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 9. 9. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 9. 0. 9. 9. 0. 0. 0. 0. 0.]
 [9. 0. 0. 9. 0. 9. 9. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 9.]
 [9. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9. 9. 0. 9. 0. 0.]]


In [46]:

X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.13559219  0.03845266 -0.21583535 -0.0859727   0.12996116 -0.19146551
   0.23975     0.23526932 -0.29352881  0.00777703]
 [-0.14349898 -0.43843484 -0.44753207  0.34762366  0.35950008 -0.44594891
   0.1521449   0.33214329  0.13579218  0.1482107 ]
 [-0.3506043   0.17923954 -0.1268356  -0.07820576  0.10450135 -0.24894297
  -0.38259086  0.33669267  0.4310935   0.13565244]
 [-0.49757082 -0.05665878  0.07572498  0.11228087  0.1703575   0.35736849
  -0.2864281  -0.01897758  0.24290081 -0.09899737]
 [-0.29542431  0.13051017 -0.32846421  0.19855465 -0.47354449  0.29926393
  -0.202192    0.04098443  0.21443627  0.41587556]]


In [62]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 6 4]
 [8 4 8]
 [1 4 4]]
[[8 4 8]
 [1 4 4]
 [9 6 4]]


In [63]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [64]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4957831211948406


In [ ]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

In [65]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 4. 5. 1. 4. 2. 4. 4. 1. 3.]


In [66]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [67]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [68]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[48 52 38 35]
 [71 48 41 53]
 [48 44 67 43]]


In [69]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.50234884 0.32187892 0.38806891 0.56874911 0.47196783 0.57351067
 0.64228436 0.50673641 0.4436527  0.49435164]


In [70]:

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)

array([1.66148109, 0.74255311, 1.10452096, 1.40710921, 1.20689109])

In [71]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

In [73]:
faces = np.random.randint(0,100,(10,3))
print(faces)
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[[ 6 80 90]
 [13 55 99]
 [ 7 79 11]
 [53 95 17]
 [45 26  6]
 [11  5 12]
 [84  6 91]
 [97 77 82]
 [60 33 81]
 [57 99 69]]
[( 5, 11) ( 5, 12) ( 6, 26) ( 6, 45) ( 6, 80) ( 6, 84) ( 6, 90) ( 6, 91)
 ( 7, 11) ( 7, 79) (11, 12) (11, 79) (13, 55) (13, 99) (17, 53) (17, 95)
 (26, 45) (33, 60) (33, 81) (53, 95) (55, 99) (57, 69) (57, 99) (60, 81)
 (69, 99) (77, 82) (77, 97) (80, 90) (82, 97) (84, 91)]


In [74]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [76]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))





# from numpy.lib.stride_tricks import sliding_window_view

# Z = np.arange(20)
# print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [77]:

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.9029882 , -0.59367795,  0.48775178, -0.76152566,  0.55366174,
       -0.43300238,  0.88319684,  0.18643119, -0.71449802, -0.68503576,
        0.65047473,  0.92234678,  0.28888111,  0.65397524, -0.40298156,
        0.223315  , -0.48004055,  0.15122571,  0.37486144,  0.84535771,
        0.25315496, -0.41785208,  0.32617227,  0.96097506, -0.78745437,
        0.78944914, -0.47978836,  0.55772304,  0.799788  , -0.00265853,
       -0.3953473 ,  0.65192083,  0.83588591, -0.56191188,  0.45075356,
        0.68251097,  0.64472766, -0.32279662,  0.58367827,  0.38437725,
       -0.41545559, -0.63101783,  0.94404052,  0.91180898, -0.89093899,
        0.77956556,  0.61724629,  0.43001421,  0.06769383, -0.70684116,
        0.78628459, -0.67784341,  0.55256112, -0.77684058,  0.44923115,
       -0.58268056, -0.93417242,  0.57159009,  0.91529086,  0.49911969,
        0.059997  , -0.43407847,  0.06193897, -0.28885807, -0.21477759,
        0.82661845,  0.21187351,  0.67701744,  0.68252169, -0.08