In [2]:
import numpy as np

In [3]:
a = np.random.uniform(0,10,10)

print(a - a%1)
print(a // 1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[7. 5. 9. 9. 8. 0. 0. 7. 7. 4.]
[7. 5. 9. 9. 8. 0. 0. 7. 7. 4.]
[7. 5. 9. 9. 8. 0. 0. 7. 7. 4.]
[7 5 9 9 8 0 0 7 7 4]
[7. 5. 9. 9. 8. 0. 0. 7. 7. 4.]


In [5]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [6]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [7]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [8]:
b = np.random.random(10)
b.sort()
print(b)

[0.1148784  0.19999552 0.32830788 0.37211311 0.52865215 0.69703177
 0.74203851 0.95900755 0.964927   0.97038465]


In [10]:
x = np.arange(10)
np.add.reduce(x)

45

In [11]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
np.array_equal(A,B)
np.array_equiv(A,B)



[0 0 0 1 1] [0 1 1 0 1]


False

In [14]:
A = np.random.randint(0,2,5)
A.flags.writeable=None
A[0]=1
A


ValueError: assignment destination is read-only

In [16]:
a=np.random.randint(0,10,(10,2))
print(a)
x,y=a[:,0],a[:,1]
x,y
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
r,t

[[9 5]
 [1 1]
 [8 6]
 [1 4]
 [5 4]
 [2 2]
 [5 0]
 [6 2]
 [5 9]
 [2 8]]


(array([10.29563014,  1.41421356, 10.        ,  4.12310563,  6.40312424,
         2.82842712,  5.        ,  6.32455532, 10.29563014,  8.24621125]),
 array([0.5070985 , 0.78539816, 0.64350111, 1.32581766, 0.67474094,
        0.78539816, 0.        , 0.32175055, 1.06369782, 1.32581766]))

In [18]:
a=np.random.randint(0,100,(10))
print(a)
a[np.argmax(a)]=0
a

[87 40 62 51 17 77 24 63 47 31]


array([ 0, 40, 62, 51, 17, 77, 24, 63, 47, 31])

In [19]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
