In [19]:
import numpy as np
import sys

Array conversion from 1D to 2D "Adding new index"
inserting a newaxis in first position results in adding new axis in row else it will be inserted in column

In [20]:
a=np.array([1,2,3,4,5,6])
a.shape
a2=a[np.newaxis,:]
a2.shape
a3=a[np.newaxis,:]
a3.shape


(1, 6)

indexing the array 'a'can also be done with the help of the constraints

In [21]:
# print(a)
# print(a[1:])
# print(a[1:2])
# print(a[-1])
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[1:])
print(a[1:2])
print(a[a%2==0])
print(a[(a>5)&(a%2==0)])
print(a[(a>5)|(a%2==0)])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[5 6 7 8]]
[ 2  4  6  8 10 12]
[ 6  8 10 12]
[ 2  4  6  7  8  9 10 11 12]


In [22]:
b=np.nonzero(a<5)
print(b)
x=list(zip(b[0],b[1]))



(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [23]:
a= np.arange(1, 25).reshape(2, 12)
print(a)
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
np.vstack((a1,a2))
np.hstack((a1,a2))
np.hsplit(a,(3,7))
# np.vsplit(a,2)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

In [24]:
p=np.random.rand(4,2)
q=np.random.randint(7,size=(3,3))
p
q

array([[6, 3, 6],
       [4, 0, 0],
       [1, 2, 1]])

In [25]:
rng=np.random.default_rng(10)
rng.random((3,3))
x=rng.integers(1,7,(5,5))
rng=np.random.default_rng()
rng.integers(75,size=(10,10))

In [26]:
print(x)
x.T
help(max)

[[4 6 2 5 1]
 [3 5 4 6 5]
 [6 5 1 6 6]
 [1 6 5 2 1]
 [3 6 5 2 3]]
Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [27]:

np.unique(x,return_index=True,return_counts=True)
np.flip(x,axis=0)

array([[3, 6, 5, 2, 3],
       [1, 6, 5, 2, 1],
       [6, 5, 1, 6, 6],
       [3, 5, 4, 6, 5],
       [4, 6, 2, 5, 1]], dtype=int64)

In [28]:

z=np.arange(40).reshape(5,2,2,2)
np.set_printoptions(threshold=sys.maxsize)
print(z)
indices=[3,1,1,1] 
z[indices]

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]


 [[[24 25]
   [26 27]]

  [[28 29]
   [30 31]]]


 [[[32 33]
   [34 35]]

  [[36 37]
   [38 39]]]]


array([[[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [29]:
a=np.arange(1,21).reshape(20,1)
b=np.arange(1,11).reshape(1,10)
a*b


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120],
       [ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130],
       [ 14,  28,  42,  56,  70,  84,  98, 112, 126, 140],
       [ 15,  30,  45,  60,  75,  90, 105, 120, 135, 150],
       [ 16,  32,  48,  64,  80,  96, 112, 128, 144, 160],
       [ 17,  34,  51,  68,  85, 102, 119, 136, 153, 170

In [30]:


a = np.array([[1, 2],
			[3, 4]])

b = np.array([[5, 6],
			[7, 8]])
c = [5, 6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((a, c)))

# concatenation method
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 0))



Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
