In [2]:
import numpy as np

Array conversion from 1D to 2D "Adding new index"
inserting a newaxis in first position results in adding new axis in row else it will be inserted in column

In [6]:
a=np.array([1,2,3,4,5,6])
a.shape
a2=a[np.newaxis,:]
a2.shape
a3=a[np.newaxis,:]
a3.shape


array([[1, 2, 3, 4, 5, 6]])

indexing the array a=can also be done with the help of the constraints

In [34]:
# print(a)
# print(a[1:])
# print(a[1:2])
# print(a[-1])
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[1:])
print(a[1:2])
print(a[a%2==0])
print(a[(a>5)&(a%2==0)])
print(a[(a>5)|(a%2==0)])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[5 6 7 8]]
[ 2  4  6  8 10 12]
[ 6  8 10 12]
[ 2  4  6  7  8  9 10 11 12]


In [24]:
b=np.nonzero(a<5)
print(b)
x=list(zip(b[0],b[1]))



(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


[(0, 0), (0, 1), (0, 2), (0, 3)]

In [42]:
a= np.arange(1, 25).reshape(2, 12)
print(a)
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
np.vstack((a1,a2))
np.hstack((a1,a2))
np.hsplit(a,(3,7))
# np.vsplit(a,2)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

In [74]:
p=np.random.rand(4,2)
q=np.random.randint(4,7,size=(3,3))
p
q

array([[5, 4, 5],
       [5, 4, 6],
       [6, 5, 6]])